apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: auth

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: deepak201994/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: deepak201994/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .

    - image: deepak201994/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: deepak201994/order
      context: order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: deepak201994/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: deepak201994/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .        
  local:
    push: false

deploy:
  kubectl:
    manifests:
      - auth/infra/k8s/*.yaml
